vich_uploader:
    db_driver: orm

    mappings:
        artiste_avatars:
            uri_prefix: /uploads/avatars
            upload_destination: '%kernel.project_dir%/public/uploads/avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        oeuvres_images:
            uri_prefix: /uploads/oeuvres
            upload_destination: '%kernel.project_dir%/public/uploads/oeuvres'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer




